const BlogPage = () => {
    return (
        <div className="container">
            <h1>ブログ</h1>

            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet impedit praesentium quam ex aliquid explicabo architecto, voluptate sed perferendis natus animi enim? Quibusdam, voluptas ab deleniti laborum recusandae ullam sit et repellat placeat accusantium optio nihil dolores, nobis quia? Alias iusto tenetur nihil reprehenderit in distinctio dolor atque perspiciatis unde asperiores, quae accusantium vel beatae quos quis voluptate accusamus? Blanditiis dolores neque temporibus, nobis modi eos nam exercitationem! Dicta ipsam consectetur error sequi explicabo quisquam, delectus laudantium, deleniti debitis officiis ipsum quaerat magni aspernatur excepturi suscipit eos fuga! Magnam cum illo aut incidunt dignissimos ipsa. Nam, adipisci. Tempore, sit? Natus.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet impedit praesentium quam ex aliquid explicabo architecto, voluptate sed perferendis natus animi enim? Quibusdam, voluptas ab deleniti laborum recusandae ullam sit et repellat placeat accusantium optio nihil dolores, nobis quia? Alias iusto tenetur nihil reprehenderit in distinctio dolor atque perspiciatis unde asperiores, quae accusantium vel beatae quos quis voluptate accusamus? Blanditiis dolores neque temporibus, nobis modi eos nam exercitationem! Dicta ipsam consectetur error sequi explicabo quisquam, delectus laudantium, deleniti debitis officiis ipsum quaerat magni aspernatur excepturi suscipit eos fuga! Magnam cum illo aut incidunt dignissimos ipsa. Nam, adipisci. Tempore, sit? Natus.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet impedit praesentium quam ex aliquid explicabo architecto, voluptate sed perferendis natus animi enim? Quibusdam, voluptas ab deleniti laborum recusandae ullam sit et repellat placeat accusantium optio nihil dolores, nobis quia? Alias iusto tenetur nihil reprehenderit in distinctio dolor atque perspiciatis unde asperiores, quae accusantium vel beatae quos quis voluptate accusamus? Blanditiis dolores neque temporibus, nobis modi eos nam exercitationem! Dicta ipsam consectetur error sequi explicabo quisquam, delectus laudantium, deleniti debitis officiis ipsum quaerat magni aspernatur excepturi suscipit eos fuga! Magnam cum illo aut incidunt dignissimos ipsa. Nam, adipisci. Tempore, sit? Natus.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet impedit praesentium quam ex aliquid explicabo architecto, voluptate sed perferendis natus animi enim? Quibusdam, voluptas ab deleniti laborum recusandae ullam sit et repellat placeat accusantium optio nihil dolores, nobis quia? Alias iusto tenetur nihil reprehenderit in distinctio dolor atque perspiciatis unde asperiores, quae accusantium vel beatae quos quis voluptate accusamus? Blanditiis dolores neque temporibus, nobis modi eos nam exercitationem! Dicta ipsam consectetur error sequi explicabo quisquam, delectus laudantium, deleniti debitis officiis ipsum quaerat magni aspernatur excepturi suscipit eos fuga! Magnam cum illo aut incidunt dignissimos ipsa. Nam, adipisci. Tempore, sit? Natus.</p>
        </div>
    )
}

export default BlogPage
